### ISSUE TITLE
Support new features in Android 7.1 Developer Preview

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/shadowsocks-android#950]
## TODO

* [x] Add [`android:roundIcon`](https://developer.android.com/preview/api-overview.html#circular-icons);
* [x] Make use of the [demo mode API](https://developer.android.com/reference/android/os/UserManager.html#isDemoUser());
* [x] Add static [app shortcut](https://developer.android.com/preview/shortcuts.html). (dynamic ones should be considered after fixing #762)

**Comment by Mygod** [comment]
![screenshot_1477203805](https://cloud.githubusercontent.com/assets/3511321/19624523/71fa944c-992c-11e6-9bb1-bd2937bd726d.png)
Left: Android 7.1 shortcut (bug: double shadow)
Right: Backward compatible shortcut

TODO: Design shortcut icon according to [the guidelines which doesn't exist yet](https://material.google.com/style/icons.html#icons-launcher-shortcut-icons).

**Comment by Mygod** [comment]
![image](https://cloud.githubusercontent.com/assets/3511321/19854827/10ab416a-9fac-11e6-8a86-6c0a040d32b7.png)
Shortcut icons designed based on [Google's Messenger app](https://play.google.com/store/apps/details?id=com.google.android.apps.messaging). [Design source](https://mygod.be/resources/userscloud/ai93fqgxbxbm).
